### ISSUE TITLE
RFE: please allow use system installed ninja binary

### ISSUE THREAD

**Issue by kloczek** [scikit-build/ninja-python-distributions#156] opened 2022-11-05 14:27 UTC
Please allow use system installed ninja binary instead bundled one.

**Comment by maxbachmann** [comment] 2022-11-30 19:17
You can perform this check in your own build system and dynamically add this package as build dependency when it is not available on the system. I started to use this approach in my packages: https://github.com/maxbachmann/RapidFuzz/blob/main/_custom_build/backend.py.
This approach has been adopted by meson-python: https://github.com/mesonbuild/meson-python/pull/175 and scikit-build: https://github.com/scikit-build/scikit-build-core/pull/5 as well.

**Comment by eli-schwartz** [comment] 2022-12-01 02:12
This is just a duplicate of #127 though. That issue has some of the background discussion that led to @henryiii implementing this for both scikit-build and meson-python.

(It would still be interesting to have a convenient way to pass a flag and build dummy metadata to satisfy projects that ended up with a forced ninja dependency. But that is a much lower priority.)

**Comment by henryiii** [comment] 2022-12-01 02:14
Closing as duplicate of #127.

**Closed by henryiii** 2022-12-01 02:14 UTC
